trigger:
- main

pool:
  name: 'sast'
  demands:
    - agent.name -equals sast

steps:
- checkout: self
  displayName: "Checkout Repository"

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'my-python-app'
    cliProjectName: 'My Python App'
    cliSources: '.'
    extraProperties: |
      sonar.branch.name=
  displayName: "Prepare SonarQube Analysis"

- task: SonarQubeAnalyze@5
  displayName: "Run SonarQube Analysis"

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: "Publish SonarQube Quality Gate Results"

