trigger:
  - main   # or your branch

pool:
  name: 'sast'         # your custom pool
  demands:
    - agent.name -equals sast   # your agent name

steps:
  # 1. Checkout code
  - checkout: self

  # 2. Prepare SonarQube Analysis
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'Sonarqube'   # the service connection you created
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'my-app'
      cliProjectName: 'My Application'
      cliSources: '.'

  

  # 4. Run SonarQube Analysis
  - task: SonarQubeAnalyze@5
    displayName: 'Run SonarQube analysis'

  # 5. Publish Quality Gate result
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish SonarQube Quality Gate results'
